### ISSUE TITLE
Can't use Regions.sample with LabelRegions

### ISSUE THREAD

**Issue by seebacherd** [imglib/imglib2-roi#18]
Regions.sample expects an IterableInterval of type < B extends BooleanType< B >> but a LabelRegion is of type IterableInterval< Void >, therefor you can't use Regions stuff with LabelRegions.

**Comment by tpietzsch** [comment]
Thanks @seebacherd Good catch. Looks like we missed Regions.sample in the recent change to Void. I'll fix it.

**Comment by tpietzsch** [comment]
it should work now.

**Comment by tpietzsch** [comment]
I released imglib2-roi 0.4.1, which contains the fix
