### ISSUE TITLE
Synchronizing update() of LabelRegions

### ISSUE THREAD

**Issue by dietzc** [imglib/imglib2-roi#19]
https://github.com/imglib/imglib2-roi/blob/master/src/main/java/net/imglib2/roi/labeling/LabelRegions.java#L333

Shouldn't the generation check be synchronized, too? If I have to processes running in parallel both will update the list, even if generations match after the first thread has updated all lists.

**Comment by tpietzsch** [comment]
@dietzc Probably you are right. I think also something has to be done about https://github.com/imglib/imglib2-roi/blob/master/src/main/java/net/imglib2/roi/labeling/LabelRegion.java#L147
I'll need to look at it in more detail.

**Comment by dietzc** [comment]
The unsynchronized `update()` causes also concurrent modification exceptions (if thread one updates while thread two accesses the existing labels).

**Comment by tpietzsch** [comment]
can you give a more detailed scenario and stacktrace of exception?

**Comment by dietzc** [comment]
I will try to write a reproducible test.

**Comment by dietzc** [comment]
see: https://gist.github.com/dietzc/fa6eac96791b67c2fed4 it's not too easy to reproduce outside KNIME. However, the problem becomes visible if you run this test and set a breakpoint in line https://gist.github.com/dietzc/fa6eac96791b67c2fed4#file-gistfile1-txt-L54 and then step into `getExistingLabels()` (one thread after the other) and run them as soon as they passed the `generation` check in the `update()`, then you will experience a `ConcurrentModificationException`.

**Comment by dietzc** [comment]
More problems related to `getExistingLabels()`: If we don't synchronize the generation check, potentially Thread A may get an empty existing labels list (as generation is the same, but list has not been updated by the Thread which is updating at the moment).

**Comment by dietzc** [comment]
fixed with https://github.com/imglib/imglib2-roi/commit/f31dc3964f628ed704f33e9201696df76a55b1a2
