### ISSUE TITLE
Ellipsoid

### ISSUE THREAD

**Issue by tibuch** [imglib/imglib2-roi#28]
I am improving the geometric 2d feature tests in imagej-ops https://github.com/imagej/imagej-ops/issues/449. Since I couldn't verify the major- and minor-axis numbers I took a closer look at the implementation. Currently [ImageJ1 code which is adapted to work with a Polygon](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/geom/geom2d/DefaultMinorMajorAxis.java#L60) is used to find the fitting ellipse from which major- and minor-axis are extracted.  

Since I couldn't verify the numbers I opened this discussion https://github.com/imagej/imagej-ops/issues/452 which ended up in this PR https://github.com/imagej/imagej-ops/pull/453 which would decouple the fitting ellipse implementation from the major- and minor-axis implementation and could be tested against a matlab-implementation. 

This is not the best solution, because this implementation is based on the deprecated ellipse implementation. In discussion with @tpietzsch and @dietzc I found other implementations of HyperEllipsoids and fitting ellipse algorithms. 

What do we have:
- Minor-Major-Axis implementation in imagej-ops which I can't verify and would like to replace.
- The currently used ellipse implementation in [imagej-ops is deprecated](https://github.com/imglib/imglib2-roi/blob/master/src/main/java/net/imglib2/roi/EllipseRegionOfInterest.java). 
- @axtimwalde has an open issue about HyperEllipsoid https://github.com/imglib/imglib2-algorithm/issues/23
- @tpietzsch has an implementation of Hyperellipsoid and some functionality https://github.com/imglib/imglib2-algorithm/compare/ellipsoid-fitting
- @haesleinhuepf has a PR which includes an n-dimensional ellipsoid https://github.com/imglib/imglib2-roi/pull/25
- my PR of a fitting ellipsoid implementation, which is based on the deprecated ellipsoid https://github.com/imagej/imagej-ops/pull/453

What I would suggest:
- An ellipse implementation on imglib2 side.
- A fitting ellipse implementation on imglib2 side or on imagej-ops side. 

I am happy to contribute, the question is just where to continue.

**Comment by maierl** [comment]
There's another 3D Ellipsoid implementation available as ImageJ plugin:

**Comment by tibuch** [comment]
I was able to verify the major-minor-axis implementation. 

The best fitting ellipse in the major-minor-axis case, is the one with the "same" area. which is different from the referenced implementations which fit an ellipse to a point cloud. 

Also ellipse is part of this discussion: http://forum.imagej.net/t/implementation-plan-for-imglib2-rois-2d/2531/1
