### ISSUE TITLE
Contains interface is gone :-(

### ISSUE THREAD

**Issue by haesleinhuepf** [imglib/imglib2-roi#47]
Dear all,

I just fall over the removal of the `Contains` interface. Find details here:
https://forum.image.sc/t/examples-of-usage-of-imglib2-roi/22855/25

I really like the annotation "@Deprecated" because it allows developers to deal with issues before they happen. Would it be possible to bring the Contains interface back, deprecate it and remove it in - let's say half a year?

Sorry for being a bit grumpy.

Cheers,
Robert

**Comment by ctrueden** [comment]
@haesleinhuepf I feel your pain.

Some additional details:
* It was removed almost two years ago (see 6f6a259d082f10460c0f3750d5c29c89b7ddc298). The first imglib2-roi release without it was imglib2-roi 0.5.0.
* The first pom-scijava release with imglib2-roi 0.5.0 was pom-scijava 20.0.0 (see scijava/pom-scijava@3a5f5516c53614c9761cb4c752d73ff5c523946d).
* Fiji's pom-scijava advanced beyond that point on the master branch on April 30, 2018 (see fiji/fiji@5b9e6e9d18c240ffe882e5667f23c6b392e7cff6).
* The first Fiji release to incorporate this update was [2.0.0-pre-5](https://github.com/fiji/fiji/releases/tag/fiji-2.0.0-pre-5) on May 25, 2018.

So I fear your `Contains`-related functionality has been broken for more than 8 months now. 😞 

Would bringing back the interface fix your functionality? Just bringing back the interface deprecated might not be enough, depending on what you do with the `BinaryUnion` et al. classes. Do they get passed to other things in the imglib2-roi API? Would the places where they get passed still work as desired with something implementing such a deprecated and orphaned interface?
