### ISSUE TITLE
Utility methods to remap labels of labelings

### ISSUE THREAD

**Issue by imagejan** [imglib/imglib2-roi#54]
I was considering adding a utility method to transform `ImgLabeling`s by mapping the existing labels `T` to some new labels `U`, given a `Function<T,U>`.

```
ImgLabeling<U,I> remapLabels( ImgLabeling<T,I> labeling, Function<T,U> function )
```

This would be similar to what the [*Label Transformer* node](https://github.com/knime-ip/knip/blob/0a0050a916aef907d875890483026fb5cb2b7c59/org.knime.knip.base/src/org/knime/knip/base/nodes/seg/labeleditor/LabelTransformerNodeFactory.java#L157-L176) in `knime-ip/knip` is currently doing.

Two questions:

* Is there any interest to have this as a static method in `net.imglib2.roi.labeling.Labelings`?
* What's the best way to approach this?
  I was thinking of getting the `LabelingMapping<T>` from the input, transforming its labels `Set<T>` to new sets of labels `Set<U>` with the given function, and then creating a new `ImgLabeling<U> result` with the same index image, and setting the labels with `result.getMapping().setLabelSets(newLabelSets)`.
  Is this any better than simply creating a new labeling and iterating over input and output with two `Cursor`s?

**Comment by tpietzsch** [comment]
> * Is there any interest to have this as a static method in `net.imglib2.roi.labeling.Labelings`?

It would be cool to have this, absolutely!

> * Is this any better than simply creating a new labeling and iterating over input and output with two `Cursor`s?

It would be definitely much faster.

The only potential problem is if `function` is not injective. I'm not sure what would happen if you have function = {1->a, 2->a, 3->b, ... } and now the previously distinct label sets {1}, {2}, and {1,2} all become {a}. But if it is a problem, we could just point out in the javadoc that is is not allowed.
