### ISSUE TITLE
Create LabelingType of different label type

### ISSUE THREAD

**Issue by dietzc** [imglib/imglib2-roi#7]
@tpietzsch another one: 

to create a `LabelingType<L>` I usually use the underlying `RandomAccessibleInterval<LabelingType<L>>` and create another variable from the first element. However, assume you want to create a `LabelingType<V>`. There is no way to create an empty `LabelingType<V>` without having another `LabelingType<V>` at hand. Could we add a helper method for that to LabelingType?

`static <V> createLabelingType(final Class<V> v){
...
}`?

Use-case: Read-only converters.

**Comment by tpietzsch** [comment]
@dietzc Sounds good. You could add it to ```net.imglib2.roi.util.Util```

**Comment by dietzc** [comment]
@tpietzsch how would I do it outside the `LabelingType`?

**Comment by tpietzsch** [comment]
right, the constructor is protected... yes, then in the LabelingType

**Comment by dietzc** [comment]
I will make a PR.

**Comment by ctrueden** [comment]
I know I am super anal about this, but can be consider renaming the class called `Util`? I really like how ImgLib2 (and core Java e.g. `Arrays`) name some utility classes with plurals. We could have a utility class called `ROIs`.

**Comment by tpietzsch** [comment]
@ctrueden Sure, lets rename it! How about ```RoiUtils```? I would like to reserve ```Regions``` for the ```Views```-like static methods and ```ROIs``` maybe comes confusingly close.

**Comment by ctrueden** [comment]
@tpietzsch OK, how about `ROIUtils` then? The SciJava naming convention is to avoid camel-casing acronyms, but instead keep them up-case. Though if you want to establish a different convention for ImgLib2 naming in general, I am OK with that, as long as it's consistent.

**Comment by tpietzsch** [comment]
@ctrueden I have no strong preference. ```ROIUtils``` is fine.
